# Top Survivor Config #

# Number of players to display in the sidebar
# Default is 5
Display.Count: 5

# Enable Log Files on reset
# Default is true
LogFile: true

# AfkTerminator multiplier (in ticks)
# Default is 24000 ticks (one day)
AfkTerminatorPenalty: 24000

# Time between updating all online players (in ticks)
# Default is 24000 ticks (one day)
RefreshTime: 24000

# Toggle to poll for AFKTerminator
AfkTerminator: true

# Time to poll for players using AFKTerminator (in ticks)
# Default is 1200
AfkTerminatorPoll: 1200

# Length of contest time (in IRL days) 
# Default is 30 days
Contest.Length: 30

# When the contest started (in milliseconds)
# Default is 0 (not in progress)
# For internal use only
# Don't mess with it unless you know what you are doing
Contest.Start: 0

# Flags #
# These are for internal use only
# Don't mess with these unless you know what you are doing

Flag.Contest: false
Flag.UpdatePlayerFiles: true
