main: com.retrontology.topsurvivor
name: TopSurvivor
version: 0.1
author: Retrontology
description: A plugin that creates a scoreboard system from players time since last death, with afk time subtracted
commands:
   reset:
      description: Reset the scoreboard
      usage: /topsurvivor reset
      permission: topsurvivor.reset
      permission-message: You're not supposed to be here :I
   view:
      description: View the top survivors
      usage: /topsurvivor
      permission: topsurvivor.citizen
      permission-message: Become a citizen to view the full Top Survivor board