main: com.retrontology.topsurvivor.TopSurvivor
name: TopSurvivor
version: 0.1
author: Retrontology
description: A plugin that creates a scoreboard system from players time since last death, with afk time subtracted
commands:
  topsurvivor:
    description: Commands to manage Top Survivors
    aliases: [ts, topsurvivors] 
    usage: |
      Use /help topsurvivor [subcommand] for more information
      /topsurvivor - View Top Survivor Leaderboard
      /topsurvivor view - View Top Survivor Leaderboard
      /topsurvivor reset - Reset Top Survivor Leaderboard
      /topsurvivor update - Update Top Survivor Leaderboard
  topsurvivor view:
    description: View Top Survivor Leaderboard
    aliases: [topsurvivor v]
    usage: |
      /topsurvivor view
  topsurvivor reset:
    description: Reset Top Survivor Leaderboard
    usage: |
      /topsurvivor reset
  topsurvivor update:
    description: Update Top Survivor Leaderboard
    usage: |
      /topsurvivor update