main: com.retrontology.topsurvivor.TopSurvivor
name: TopSurvivor
version: 0.9.1
author: Retrontology
description: A plugin that creates a scoreboard system from players time since last death, with afk time subtracted
permissions: 
  topsurvivor.citizen:
    description: Required for viewing leaderboard via command
    default: false
  topsurvivor.admin:
    description: Required for server admin commands such as reset, update, etc
    default: false
commands:
  topsurvivor:
    description: View Top Survivor Leaderboard
    aliases: [ts, topsurvivors] 
    permission: topsurvivor.citizen
    permission-message: Become a citizen to view the Top Survivor Board
    usage: |
      /topsurvivor - View Top Survivor Leaderboard
      /topsurvivor view <page/player>- View Top Survivor Leaderboard
      /topsurvivor reset - Reset Top Survivor Leaderboard
      /topsurvivor update - Update Top Survivor Leaderboard
      /topsurvivor tempban <player> - Ban a player until the board is reset
      /topsurvivor permaban <player> - Ban a player until they are unbanned
      /topsurvivor unban <player> - Unban a player from the board
      /topsurvivor afktpenalty - Modify a players AFKTerminator Penalty
  topsurvivor view:
    description: View Top Survivor Leaderboard
    aliases: [topsurvivor v]
    permission: topsurvivor.citizen
    permission-message: Become a citizen to view the Top Survivor Board
    usage: |
      /topsurvivor view [player/page]
  topsurvivor reset:
    description: Reset Top Survivor Leaderboard
    permission: topsurvivor.admin
    permission-message: What do you think you are doing :I
    usage: |
      /topsurvivor reset
  topsurvivor update:
    description: Update Top Survivor Leaderboard
    permission: topsurvivor.admin
    permission-message: What do you think you are doing :I
    usage: |
      /topsurvivor update
  topsurvivor tempban:
    description: Ban player until the scoreboard is reset
    aliases: [topsurvivor ban, ts ban]
    permission: topsurvivor.admin
    permission-message: What do you think you are doing :I
    usage: |
      /topsurvivor tempban <player>
  topsurvivor permaban:
    description: Ban player until they are unbanned
    permission: topsurvivor.admin
    permission-message: What do you think you are doing :I
    usage: |
      /topsurvivor permaban <player>
  topsurvivor unban:
    description: Unban a player and let them start participating immediately
    permission: topsurvivor.admin
    permission-message: What do you think you are doing :I
    usage: |
      /topsurvivor unban [player]
  topsurvivor afktpenalty:
    description: Modify a player's AFKTerminator penalty
    permission: topsurvivor.admin
    permission-message: What do you think you are doing :I
    usage: 